version: '3.8'  # Specifies the Docker Compose version
 
services:
  web:
    image: node:16  # Uses Node.js image
    build: 
      context: ./app  # Path to Dockerfile for the web service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Maps port 3000 on host to 3000 in container
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    depends_on:
      - db  # Ensures database starts before web service
    volumes:
      - ./app:/usr/src/app  # Mounts local app directory to container
    networks:
      - my-network
 
  db:
    image: postgres:13  # Uses PostgreSQL image
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data  # Persists database data
    networks:
      - my-network

volumes:
  db-data:
networks:
  my-network:
